# Generated by Django 5.1 on 2024-11-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0012_remove_quires_answer_remove_quires_a_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='qanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('a_img', models.ImageField(blank=True, upload_to='qu_img')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.quires')),
            ],
        ),
    ]
