# Generated by Django 5.1 on 2024-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assignment_lecture_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
