# Generated by Django 5.1 on 2024-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_completecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up_table',
            name='amount',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sign_up_table',
            name='razor_payemnt_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
